name:                aoc
version:             0.1.0.0
github:              "Rekwass/AdventOfCode"
license:             BSD3
author:              "Nicolas MOINARD"
maintainer:          "rekwass@gmail.com"
copyright:           "Copyright (c) 2024, Nicolas MOINARD"

description:         Please see the README on GitHub at <https://github.com/Rekwass/AdventOfCode#readme>

dependencies:
- base >= 4.7 && < 5
- split >= 0.2.5
- pcre-heavy >= 1.0.0.3
- containers >= 0.6.7
- multiset >= 0.3.4.3
- matrix >= 0.3.6.3
- linear >= 1.22
- search-algorithms >= 0.3.2
- psqueues >= 0.2.8.0
- hashable >= 1.4.3.0
- lens >= 5.2.3
- MemoTrie >= 0.6.11
- composition >= 1.0.2.2

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  aoc-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc
